import { describe, expect, it } from "vitest";
import { promises as fs } from "node:fs"; import os from "node:os"; import path from "node:path";
import { builtInProductionTemplates, importExistingBackup, previewExistingBackup, projectCoverage } from "../src/main/production-lifecycle";
import { generateMhl } from "../src/main/backup/ManifestGenerator";
const project:any={id:"p",name:"Film",devices:["FX3"],volumePrefix:"A_",requiredCopies:2,expectedVolumes:4,managedSince:"2026-08-01"};
describe("0.1.0 production lifecycle",()=>{
  it("recognizes and safely baselines an existing backup",async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"kocpy-import-"));try{await fs.mkdir(path.join(root,"20260801","FX3_A","CARD01"),{recursive:true});await fs.mkdir(path.join(root,"20260801","FX3_B","CARD02"),{recursive:true});await fs.writeFile(path.join(root,"20260801","FX3_A","CARD01","clip.mov"),"media");await fs.writeFile(path.join(root,"20260801","FX3_B","CARD02","clip.mov"),"media2");const preview=await previewExistingBackup(root);expect(preview.files).toBe(2);expect(preview.candidates).toHaveLength(2);expect(preview.candidates.every((item)=>item.shootingDate==="2026-08-01")).toBe(true);const task=await importExistingBackup(project,path.join(root,"20260801","FX3_A","CARD01"),"external-baseline");expect(task.provenance).toBe("external-baseline");expect(task.confidence).toBe("baseline");expect(task.status).toBe("completed");}finally{await fs.rm(root,{recursive:true,force:true});}});
  it("reports coverage without pretending unknown history is complete",()=>{const coverage=projectCoverage(project,[{projectId:"p",provenance:"external-baseline",destinations:[{verified:true,path:"a"}]} as any]);expect(coverage.recorded).toBe(1);expect(coverage.compliant).toBe(0);expect(coverage.coveragePercent).toBe(25);});
  it("ships five production templates",()=>expect(builtInProductionTemplates()).toHaveLength(5));
  it("imports Kocpy legacy MHL files that use file elements",async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"kocpy-mhl-import-"));try{await fs.writeFile(path.join(root,"clip.mov"),"verified media");const source:any={id:"source",name:"CARD01",sourcePath:root,devices:[],destinations:[],hashAlgorithm:"sha256",namingTemplate:"CARD01",status:"completed",totalFiles:1,completedFiles:1,totalBytes:14,transferredBytes:14,speedBps:0,eta:0,currentFile:"",verifyLog:[],fileRecords:[{name:"clip.mov",relativePath:"clip.mov",size:14,srcChecksum:"c72e699827ff7920e04d95d3e18a88a6495efa172f45864f6cfaaee1b484447b",destinations:[]}]};await fs.writeFile(path.join(root,"CARD01.mhl"),generateMhl(source));const imported=await importExistingBackup(project,root,"manifest-import");expect(imported.status).toBe("completed");expect(imported.fileRecords[0].destinations[0].verified).toBe(true);}finally{await fs.rm(root,{recursive:true,force:true});}});
  it("keeps flat folders as one import candidate",async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"kocpy-flat-import-"));try{await fs.writeFile(path.join(root,"clip.mov"),"media");const preview=await previewExistingBackup(root);expect(preview.candidates).toMatchObject([{relativeRoot:".",files:1}]);}finally{await fs.rm(root,{recursive:true,force:true});}});
});
