import { contextBridge, ipcRenderer } from "electron";
const call =
  (channel: string) =>
  (...args: unknown[]) =>
    ipcRenderer.invoke(channel, ...args);
contextBridge.exposeInMainWorld("api", {
  resolveDroppedPaths: (files: File[]) => files.map((file) => (file as File & { path?: string }).path || "").filter(Boolean),
  selectDirectory: call("dialog:directory"),
  getTasks: call("tasks:list"),
  getCatalogStats: call("catalog:stats"),
  getCatalogFiles: call("catalog:files"),
  rebuildCatalog: call("catalog:rebuild"),
  createTask: call("tasks:create"),
  startTask: call("tasks:start"),
  cancelTask: call("tasks:cancel"),
  pauseTask: call("tasks:pause"),
  resumeTask: call("tasks:resume"),
  reverifyTask: call("tasks:reverify"),
  retryFailedDestinations: call("tasks:retry-failed"),
  deleteTask: call("tasks:delete"),
  setPriority: call("tasks:priority"),
  scanSource: call("source:scan"),
  listVolumes: call("volumes:list"),
  driveInfo: call("volumes:info"),
  ejectVolume: call("volumes:eject"),
  ejectCompletedVolumes: call("volumes:eject-completed"),
  runBenchmark: call("diagnostics:benchmark"),
  getDiagnostics: call("diagnostics:get"),
  exportDiagnostics: call("diagnostics:export"),
  getArchiveHealth: call("archive:health-list"),
  getArchiveChanges: call("archive:changes"),
  getArchiveReminders: call("archive:reminders"),
  saveArchiveReminder: call("archive:save-reminder"),
  verifyArchiveScope: call("archive:verify-scope"),
  moveArchiveCopy: call("archive:move-copy"),
  exportArchiveChanges: call("archive:export-changes"),
  verifyProjectArchive: call("archive:verify-project"),
  repairArchiveCopy: call("archive:repair-copy"),
  getProjectTemplates: call("templates:list"),
  createTemplateFromProject: call("templates:from-project"),
  deleteProjectTemplate: call("templates:delete"),
  applyProjectTemplate: call("templates:apply"),
  previewExistingBackup: call("existing:preview"),
  importExistingBackup: call("existing:import"),
  getProjectCoverage: call("projects:coverage"),
  signProjectChecklist: call("projects:sign-checklist"),
  getNasPresets: call("nas:list"),
  saveNasPreset: call("nas:save"),
  deleteNasPreset: call("nas:delete"),
  testNasPreset: call("nas:test"),
  addProjectHandoff: call("projects:add-handoff"),
  exportWorkspace: call("workspace:export"),
  importWorkspace: call("workspace:import"),
  backupWorkspaceData: call("workspace:backup-data"),
  startLanIndex: call("lan:start"),
  stopLanIndex: call("lan:stop"),
  getLanIndexStatus: call("lan:status"),
  reveal: call("system:reveal"),
  checkUpdates: call("updates:check"),
  openUpdate: call("updates:open"),
  openAuthor: call("system:open-author"),
  previewTheme: call("settings:preview-theme"),
  getSettings: call("settings:get"),
  saveSettings: call("settings:save"),
  getProjects: call("projects:list"),
  inspectProjectStructure: call("projects:inspect-structure"),
  saveProject: call("projects:save"),
  claimProjectVolume: call("projects:claim-volume"),
  exportReport: call("report:export"),
  exportDailyReport: call("report:daily"),
  exportProjectReport: call("report:project"),
  exportResolveCsv: call("report:resolve-csv"),
  inspectMedia: call("media:inspect"),
  getProxyJobs: call("proxy:list"),
  enqueueProxy: call("proxy:enqueue"),
  cancelProxy: call("proxy:cancel"),
  pauseProxy: call("proxy:pause"),
  resumeProxy: call("proxy:resume"),
  retryProxy: call("proxy:retry"),
  deleteProxy: call("proxy:delete"),
  exportProxyDelivery: call("proxy:export-delivery"),
  exportProxyPackage: call("proxy:export-package"),
  onProxyJobs: (callback: (jobs: unknown) => void) => { const listener = (_event: unknown, jobs: unknown) => callback(jobs); ipcRenderer.on("proxy:jobs", listener); return () => ipcRenderer.removeListener("proxy:jobs", listener); },
  onTaskSettled: (callback: (task: unknown) => void) => { const listener = (_event: unknown, task: unknown) => callback(task); ipcRenderer.on("tasks:settled", listener); return () => ipcRenderer.removeListener("tasks:settled", listener); },
  onProgress: (callback: (payload: unknown) => void) => {
    const listener = (_event: unknown, payload: unknown) => callback(payload);
    ipcRenderer.on("tasks:progress", listener);
    return () => ipcRenderer.removeListener("tasks:progress", listener);
  },
});
